/*
 * Copyright (c), Zeriph Enterprises
 * All rights reserved.
 * 
 * Contributor(s):
 * Zechariah Perez, omni (at) zeriph (dot) com
 * 
 * THIS SOFTWARE IS PROVIDED BY ZERIPH AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ZERIPH AND CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
 
/* DEV_NOTE: this file is not intended to be used directly by any user code!

 i.e. do not #include <omni/xxx_impl.hxx> and do not compile this source directly.
 this file is included directly in other source. 
 
 The idea is that omni::cconsts and omni::wconsts namespaces segregate the types
 for explicit calling; i.e. you can call omni::cconsts::X for a std:string type
 and similarly can call omni::wconsts::X for a std::wstring type, while still having access
 to the omni::string_t and omn::consts::X ability (which are aliases for the other namespaces).
 
 Since omni::cconsts and omni::wconsts are merely wrappers for string types
 putting the relevant code in a header with a few #defs for types makes keeping the files
 in sync (for names) less messy. It does introduce slight confusion to anyone who might
 want to read this specific code or documentation though.
*/

// so as not to accidentally build this file with the source
// these macros are defined in cconsts.hpp and wconsts.hpp
#if !defined(OMNI_CHAR_T_FW) || !defined(OMNI_STRW_FW) || !defined(OMNI_EXT_NS_FW)
    #error invalid preprocessor directive detected
#endif

OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::DELEGATE_NOT_FOUND[]= OMNI_STRW_FW(OMNI_NO_DELEGATE_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::ERR_GET_TIME[]= OMNI_STRW_FW(OMNI_ERR_GET_TIME_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::ERR_MEM_ALLOC[]= OMNI_STRW_FW(OMNI_ERR_MALLOC_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::ERR_OPEN_PARENT_PROC[]= OMNI_STRW_FW(OMNI_ERR_PROC_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::ERR_RET_PRI_CLASS[]= OMNI_STRW_FW(OMNI_ERR_PROC_PRI_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::ERR_SET_PRIORITY[]= OMNI_STRW_FW(OMNI_ERR_SET_PRI_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::FILE_NOT_FOUND[]= OMNI_STRW_FW(OMNI_FILE_NOT_FOUND_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::FILE_NOT_ACCESSIBLE[]= OMNI_STRW_FW(OMNI_FILE_NOT_ACCESSIBLE_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::GENERAL_EXCEPTION[]= OMNI_STRW_FW(OMNI_GENERAL_EXCEPTION_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INDEX_OOR[]= OMNI_STRW_FW(OMNI_INDEX_OOR_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INVALID_BASE[]= OMNI_STRW_FW(OMNI_INVALID_BASE_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INVALID_CHAR[]= OMNI_STRW_FW(OMNI_INVALID_CHAR_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INVALID_CAST[]= OMNI_STRW_FW(OMNI_INVALID_CAST_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INVALID_DELEGATE[]= OMNI_STRW_FW(OMNI_INVALID_DELEGATE_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INVALID_DELEGATE_FUNC_PTR[]= OMNI_STRW_FW(OMNI_INVALID_DELEGATE_FUNC_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INVALID_OPTION[]= OMNI_STRW_FW(OMNI_INVALID_OPTION_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INVALID_SETTING[]= OMNI_STRW_FW(OMNI_INVALID_SETTING_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INVALID_SEEK_DIR[]= OMNI_STRW_FW(OMNI_INVALID_SEEK_DIR_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INVALID_THREAD_HANDLE[]= OMNI_STRW_FW(OMNI_INVALID_THREAD_HANDLE_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INVALID_THREAD_PRIORITY[]= OMNI_STRW_FW(OMNI_INVALID_THREAD_PRIORITY_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INVALID_THREAD_START_TYPE[]= OMNI_STRW_FW(OMNI_INVALID_THREAD_START_TYPE_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::INVALID_SIZE[]= OMNI_STRW_FW(OMNI_INVALID_SIZE_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::PATH_NOT_ACCESSIBLE[]= OMNI_STRW_FW(OMNI_PATH_NOT_ACCESSIBLE_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::SET_PRI_UNSUPPORTED[]= OMNI_STRW_FW(OMNI_SET_PRI_UNSUPPORTED_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::STRING_COUNT_GT0[]= OMNI_STRW_FW(OMNI_STRING_COUNT_GT0_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::STRING_INVALID_BINARY_FORMAT[]= OMNI_STRW_FW(OMNI_STRING_INVALID_FORMAT_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::STRING_INVALID_BINARY_STR_SZ[]= OMNI_STRW_FW(OMNI_STRING_INVALID_SIZE_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::STRING_NOT_NUMERIC[]= OMNI_STRW_FW(OMNI_STRING_NOT_NUMERIC_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::SUCCESS[]= OMNI_STRW_FW(OMNI_SUCCESS_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::err::UNKNOWN[]= OMNI_STRW_FW(OMNI_UNKNOWN_STR);

OMNI_CHAR_T_FW OMNI_EXT_NS_FW::misc::COMMA = OMNI_STRW_FW(OMNI_COMMA_CHAR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::misc::MINUS = OMNI_STRW_FW(OMNI_MINUS_CHAR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::misc::NCHAR = OMNI_STRW_FW(OMNI_NCHAR_CHAR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::misc::PERIOD = OMNI_STRW_FW(OMNI_PERIOD_CHAR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::misc::PLUS = OMNI_STRW_FW(OMNI_PLUS_CHAR);

OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::full::B[]= OMNI_STRW_FW(OMNI_BYTE_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::full::KB[]= OMNI_STRW_FW(OMNI_KIBI_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::full::MB[]= OMNI_STRW_FW(OMNI_MIBI_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::full::GB[]= OMNI_STRW_FW(OMNI_GIBI_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::full::TB[]= OMNI_STRW_FW(OMNI_TIBI_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::full::PB[]= OMNI_STRW_FW(OMNI_PIBI_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::full::EB[]= OMNI_STRW_FW(OMNI_EIBI_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::full::ZB[]= OMNI_STRW_FW(OMNI_ZIBI_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::full::YB[]= OMNI_STRW_FW(OMNI_YIBI_STR);

OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::B[]= OMNI_STRW_FW(OMNI_B_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::KB[]= OMNI_STRW_FW(OMNI_KIB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::MB[]= OMNI_STRW_FW(OMNI_MIB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::GB[]= OMNI_STRW_FW(OMNI_GIB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::TB[]= OMNI_STRW_FW(OMNI_TIB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::PB[]= OMNI_STRW_FW(OMNI_PIB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::EB[]= OMNI_STRW_FW(OMNI_EIB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::ZB[]= OMNI_STRW_FW(OMNI_ZIB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::binary::string::YB[]= OMNI_STRW_FW(OMNI_YIB_STR);

OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::full::B[]= OMNI_STRW_FW(OMNI_BYTE_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::full::KB[]= OMNI_STRW_FW(OMNI_KILO_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::full::MB[]= OMNI_STRW_FW(OMNI_MEGA_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::full::GB[]= OMNI_STRW_FW(OMNI_GIGA_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::full::TB[]= OMNI_STRW_FW(OMNI_TERA_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::full::PB[]= OMNI_STRW_FW(OMNI_PETA_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::full::EB[]= OMNI_STRW_FW(OMNI_EXA_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::full::ZB[]= OMNI_STRW_FW(OMNI_ZETTA_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::full::YB[]= OMNI_STRW_FW(OMNI_YOTTA_STR);

OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::B[]= OMNI_STRW_FW(OMNI_B_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::KB[]= OMNI_STRW_FW(OMNI_KOB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::MB[]= OMNI_STRW_FW(OMNI_MOB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::GB[]= OMNI_STRW_FW(OMNI_GOB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::TB[]= OMNI_STRW_FW(OMNI_TOB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::PB[]= OMNI_STRW_FW(OMNI_POB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::EB[]= OMNI_STRW_FW(OMNI_EOB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::ZB[]= OMNI_STRW_FW(OMNI_ZOB_STR);
OMNI_CHAR_T_FW OMNI_EXT_NS_FW::size::decimal::string::YB[]= OMNI_STRW_FW(OMNI_YOB_STR);
