/*
 * Copyright (c), Zeriph Enterprises
 * All rights reserved.
 * 
 * Contributor(s):
 * Zechariah Perez, omni (at) zeriph (dot) com
 * 
 * THIS SOFTWARE IS PROVIDED BY ZERIPH AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ZERIPH AND CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#if !defined(OMNI_COLOR_DEF_HPP)
#define OMNI_COLOR_DEF_HPP 1

#if defined(OMNI_SAFE_COLOR)
    #include <omni/sync/lock.hpp>
    #include <omni/sync/scoped_lock.hpp>
    #define OMNI_SAFE_CLRDMTX_FW  ,m_mtx()
    #define OMNI_SAFE_CLRLOCK_FW   this->m_mtx.lock();
    #define OMNI_SAFE_CLRUNLOCK_FW this->m_mtx.unlock();
    #define OMNI_SAFE_CLRALOCK_FW  omni::sync::scoped_basic_lock uuid12345(&this->m_mtx);
    #define OMNI_SAFE_CLROALOCK_FW(o)  omni::sync::scoped_basic_lock uuid54321(&o.m_mtx);
#else
    #define OMNI_SAFE_CLRDMTX_FW
    #define OMNI_SAFE_CLRLOCK_FW
    #define OMNI_SAFE_CLRUNLOCK_FW
    #define OMNI_SAFE_CLRALOCK_FW
    #define OMNI_SAFE_CLROALOCK_FW(o) 
#endif

#endif // OMNI_COLOR_DEF_HPP