/*
 * Copyright (c), Zeriph Enterprises
 * All rights reserved.
 * 
 * Contributor(s):
 * Zechariah Perez, omni (at) zeriph (dot) com
 * 
 * THIS SOFTWARE IS PROVIDED BY ZERIPH AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ZERIPH AND CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#if !defined(OMNI_EXTENSION_SAFE_DEF_HPP)
#define OMNI_EXTENSION_SAFE_DEF_HPP 1

#if defined(OMNI_SAFE_EXTENSIONS)
    #define OMNI_SAFE_EXTENSION_NET
    #define OMNI_SAFE_EXTENSION_GUI
#endif

#if defined(OMNI_SAFE_EXTENSION_NET) && (defined(OMNI_NO_SAFE_EXTENSION_NET) || defined(OMNI_NO_SAFE_EXTENSIONS))
    #undef OMNI_SAFE_EXTENSION_NET
    #if !defined(OMNI_NO_SAFE_EXTENSION_NET)
        #define OMNI_NO_SAFE_EXTENSION_NET
    #endif
#endif
#if defined(OMNI_SAFE_EXTENSION_GUI) && (defined(OMNI_NO_SAFE_EXTENSION_GUI) || defined(OMNI_NO_SAFE_EXTENSIONS))
    #undef OMNI_SAFE_EXTENSION_GUI
    #if !defined(OMNI_NO_SAFE_EXTENSION_GUI)
        #define OMNI_NO_SAFE_EXTENSION_GUI
    #endif
#endif

#if defined(OMNI_SAFE_EXTENSION_NET)
    #define OMNI_SAFE_EXTENSION_NET_CLIENT
    #define OMNI_SAFE_EXTENSION_NET_SERVER
#endif
#if defined(OMNI_SAFE_EXTENSION_GUI)
    #define OMNI_SAFE_EXTENSION_GUI_APP
    #define OMNI_SAFE_EXTENSION_GUI_WINDOW
#endif

#endif // OMNI_EXTENSION_SAFE_DEF_HPP
