/*
 * Copyright (c), Zeriph Enterprises
 * All rights reserved.
 * 
 * Contributor(s):
 * Zechariah Perez, omni (at) zeriph (dot) com
 * 
 * THIS SOFTWARE IS PROVIDED BY ZERIPH AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ZERIPH AND CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES
 * LOSS OF USE, DATA, OR PROFITS OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#if !defined(OMNI_DATE_DEF_HPP)
#define OMNI_DATE_DEF_HPP 1
#include <omni/defs/global.hpp>
#include <omni/string/util.hpp>
#include <omni/types/string_t.hpp>
#include <omni/types/tick_t.hpp>

#define OMNI_DATE_PART_YEAR_FW 0
#define OMNI_DATE_PART_DAY_OF_YEAR_FW 1
#define OMNI_DATE_PART_MONTH_FW 2
#define OMNI_DATE_PART_DAY_FW 3
#define OMNI_FLAGS_MASK_FW 0xC000000000000000
#define OMNI_LOCAL_MASK_FW 0x8000000000000000
#define OMNI_KIND_UNSPECIFIED_FW 0x0000000000000000
#define OMNI_KIND_UTC_FW 0x4000000000000000
#define OMNI_KIND_LOCAL_FW 0x8000000000000000
#define OMNI_KIND_LOCAL_AMBIGUOUS_DST_FW 0xC000000000000000
#define OMNI_KIND_SHIFT_FW 62
#define OMNI_TICKS_FIELD_FW "ticks"
#define OMNI_DATE_DATA_FIELD_FW "dateData"

#endif // OMNI_DATE_DEF_HPP
