#!/bin/bash

solo()
{
    hpp=$1
    inc="#include <omni/${hpp}>"
    cpp="${hpp%.*}.cpp"
    cpp="omni_${cpp//\//_}"
    if [ -f "${cpp}" ]; then
        echo "Test already exists: ${cpp}"
    else
        echo ${inc} > ${cpp}
        echo "" >> ${cpp}
        echo "int main(int argc, char* argv[])" >> ${cpp}
        echo "{" >> ${cpp}
        echo "    return 0;" >> ${cpp}
        echo "}" >> ${cpp}
        echo "" >> ${cpp}

        echo "Created ${cpp}"
    fi
}

solo "application.hpp"
solo "argparser.hpp"
solo "bits.hpp"
solo "buffer_types.hpp"
solo "chrono/async_timer.hpp"
solo "chrono/date_time.hpp"
solo "chrono/drop_timer.hpp"
solo "chrono/queue_timer.hpp"
solo "chrono/span.hpp"
solo "chrono/stopwatch.hpp"
solo "chrono/sync_timer.hpp"
solo "chrono/tick.hpp"
solo "chrono_types.hpp"
solo "color_types.hpp"
solo "constants.hpp"
solo "consts/cconsts.hpp"
solo "consts/wconsts.hpp"
solo "crypto/md5.hpp"
solo "crypto/sha1.hpp"
solo "crypto/sha256.hpp"
solo "crypto_types.hpp"
solo "defs/32bit_def.hpp"
solo "defs/arch.hpp"
solo "defs/cancel_check_def.hpp"
solo "defs/class_macros.hpp"
solo "defs/consts.hpp"
solo "defs/crypto_def.hpp"
solo "defs/date_def.hpp"
solo "defs/debug.hpp"
solo "defs/delegate_def.hpp"
solo "defs/enum_def.hpp"
solo "defs/except_def.hpp"
solo "defs/file_def.hpp"
solo "defs/global.hpp"
solo "defs/gui_def.hpp"
solo "defs/helper.hpp"
solo "defs/lite_def.hpp"
solo "defs/macro_helper.hpp"
solo "defs/math_def.hpp"
solo "defs/net_def.hpp"
solo "defs/null_def.hpp"
solo "defs/omni_ver.hpp"
solo "defs/os.hpp"
solo "defs/safe_def.hpp"
solo "defs/thread_def.hpp"
solo "defs/tick_def.hpp"
solo "defs/timer_def.hpp"
solo "defs/win_def.hpp"
solo "delegate/0.hpp"
solo "delegate/1.hpp"
solo "delegate/10.hpp"
solo "delegate/11.hpp"
solo "delegate/12.hpp"
solo "delegate/13.hpp"
solo "delegate/14.hpp"
solo "delegate/15.hpp"
solo "delegate/16.hpp"
solo "delegate/2.hpp"
solo "delegate/3.hpp"
solo "delegate/4.hpp"
solo "delegate/5.hpp"
solo "delegate/6.hpp"
solo "delegate/7.hpp"
solo "delegate/8.hpp"
solo "delegate/9.hpp"
solo "delegates.hpp"
solo "drawing/color.hpp"
solo "drawing/known_colors.hpp"
solo "environment.hpp"
solo "exception.hpp"
solo "generic_ptr.hpp"
solo "geometry/circle.hpp"
solo "geometry/path.hpp"
solo "geometry/point2d.hpp"
solo "geometry/point3d.hpp"
solo "geometry/quadrilateral.hpp"
solo "geometry/rectangle.hpp"
solo "geometry/size.hpp"
solo "geometry/size3d.hpp"
solo "geometry/triangle.hpp"
solo "geometry/util.hpp"
solo "geometry/vector2.hpp"
solo "geometry/vector3.hpp"
solo "geometry_types.hpp"
solo "gui/window.hpp"
solo "gui_types.hpp"
solo "io.hpp"
solo "library.hpp"
solo "math.hpp"
solo "net/client.hpp"
solo "net/endpoint_descriptor.hpp"
solo "net/server.hpp"
solo "net/socket.hpp"
solo "net/util.hpp"
solo "net/version.hpp"
solo "net_types.hpp"
solo "object.hpp"
solo "ostream.hpp"
solo "property.hpp"
solo "sequence.hpp"
solo "smart_ptr.hpp"
solo "stack_buffer.hpp"
solo "string/cstring.hpp"
solo "string/util.hpp"
solo "string/wstring.hpp"
solo "strings.hpp"
solo "sync/auto_lock.hpp"
solo "sync/basic_lock.hpp"
solo "sync/basic_thread.hpp"
solo "sync/basic_thread_allocate.hpp"
solo "sync/binary_semaphore.hpp"
solo "sync/conditional.hpp"
solo "sync/lock.hpp"
solo "sync/mutex.hpp"
solo "sync/runnable.hpp"
solo "sync/runnable_thread.hpp"
solo "sync/scoped_lock.hpp"
solo "sync/semaphore.hpp"
solo "sync/spin.hpp"
solo "sync/this_thread.hpp"
solo "sync/thread.hpp"
solo "sync/thread_allocate.hpp"
solo "sync/threadpool.hpp"
solo "sync_types.hpp"
solo "system.hpp"
solo "timer_types.hpp"
solo "type.hpp"
solo "types/char_t.hpp"
solo "types/crypto_t.hpp"
solo "types/date_t.hpp"
solo "types/enum_t.hpp"
solo "types/fstream_t.hpp"
solo "types/invoke_t.hpp"
solo "types/lock_t.hpp"
solo "types/math_t.hpp"
solo "types/net_t.hpp"
solo "types/ostream_t.hpp"
solo "types/ptr_t.hpp"
solo "types/seq_t.hpp"
solo "types/string_t.hpp"
solo "types/thread_t.hpp"
solo "types/threadpool_t.hpp"
solo "types/tick_t.hpp"
solo "types/timer_t.hpp"
solo "version.hpp"
