/*
 * Copyright (c), Zeriph Enterprises
 * All rights reserved.
 * 
 * Contributor(s):
 * Zechariah Perez, omni (at) zeriph (dot) com
 * 
 * THIS SOFTWARE IS PROVIDED BY ZERIPH AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ZERIPH AND CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#include <omni/net/endpoint_descriptor.hpp>
#include <omni/net/util.hpp>
#include <omni/defs/debug.hpp>
#include <cstring>

#define OMNI_EPDESC_CONN_FLAG_FW 1
#define OMNI_EPDESC_SHUT_FLAG_FW 2

#define OMNI_NET_SOCKET4_EP_HXX_FW 1
#include "omni/xx/net/endpoint_descriptor4.hxx"
#undef OMNI_NET_SOCKET4_HXX_FW

#define OMNI_NET_SOCKET6_EP_HXX_FW 1
#include "omni/xx/net/endpoint_descriptor6.hxx"
#undef OMNI_NET_SOCKET6_HXX_FW

#if defined(OMNI_ALLOW_UNIX_SOCKET)
    #define OMNI_NET_UNIX_SOCKET_EP_HXX_FW 1
    #include "omni/xx/net/unix_endpoint_descriptor.hxx"
    #undef OMNI_NET_UNIX_SOCKET_EP_HXX_FW
#endif
